"""Step 3 of v2: cameras and metric depth for a clip, reusing v1's machinery (r2s: Depth Anything V2, instrument-shaft
scale, keyframe bundle adjustment with SIFT wide-baseline matches).

    python -m t2s.geom <clip> [seg version]   -> r2s/clips/<clip>_t2s.json, outputs/<clip>_t2s/prep/ (+ the +sift variant)

The r2s clip config is generated, not hand written: objects and roles from the scene_spec and the segmentation
(primary organ -> 'organ', other organs / tissue that moves -> 'strand', background items -> 'static', tracked
instrument instances -> 'instrument'), shaft diameters from the spec (5 mm default). The masks of the chosen
segmentation version are written as the clip's prep/masks.npz, so r2s skips its own (SAM 2.1) segmentation.
"""
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

from . import data as D

ROOT = Path(__file__).resolve().parents[1]


def r2s_name(clip):
    return f'{clip}_t2s'


def write_config(clip, seg_ver):
    info = json.loads((D.OUT / clip / 'data' / 'data.json').read_text())
    spec = json.loads((D.OUT / clip / 'spec' / 'scene_spec.json').read_text())
    q = json.loads((D.OUT / clip / 'seg' / seg_ver / 'qc.json').read_text())
    names = q['objects']
    organs = {o['name']: o for o in spec.get('organs', [])}
    primary = [n for n in names if organs.get(n, {}).get('role') == 'primary']
    shaft = next((i.get('shaft_diameter_mm') for i in spec.get('instruments', []) if i.get('shaft_diameter_mm')), 5) / 1000
    objects, instruments = {}, []
    for n in names:
        if n.startswith('instrument_'):
            objects[n] = dict(role='instrument', prompts=[])
            instruments.append(dict(name=n, mask=n, shaft_d=shaft, color='bright'))
        elif n == (primary[0] if primary else None):
            objects[n] = dict(role='organ', prompts=[])
        elif n in organs or 'membrane' in n or 'strand' in n or 'gauze' in n:
            objects[n] = dict(role='strand', prompts=[])           # moves with the instruments: not static anatomy
        else:
            objects[n] = dict(role='static', prompts=[])
    if not any(o['role'] == 'organ' for o in objects.values()):
        first = next(n for n, o in objects.items() if o['role'] == 'strand')
        objects[first]['role'] = 'organ'
    c = D.CLIPS[clip]
    a, b = c['frames']
    cfg = dict(title=f"v2 · {clip}", source=dict(type='video', path=c['video'], frames=[a, b], stride=c['stride'],
                                                 **({'crop_rows': list(c['crop_rows'])} if c['crop_rows'] else {}), fix_borders=True),
               size=info['size'], fps=info['fps'], camera=dict(fovy=47.0), objects=objects, instruments=instruments,
               note=f"generated by t2s.geom from outputs/t2s/{clip}/spec/scene_spec.json and seg/{seg_ver}", sim={}, multiview=False)
    (ROOT / 'r2s' / 'clips' / f'{r2s_name(clip)}.json').write_text(json.dumps(cfg, indent=1, ensure_ascii=False))
    return cfg


def write_masks(clip, seg_ver, cfg):
    W = cfg['size'][0]
    z = np.load(D.OUT / clip / 'seg' / seg_ver / 'masks.npz')
    m = np.stack([np.unpackbits(z[n], axis=-1)[..., :W].astype(bool) for n in cfg['objects']], 1)    # (n, objects, H, W)
    prep = ROOT / 'outputs' / r2s_name(clip) / 'prep'
    prep.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(prep / 'masks.npz', masks=np.packbits(m, axis=-1), shape=np.array(m.shape),
                        names=np.array(list(cfg['objects'])))
    return m.shape


def run(clip, seg_ver='v02'):
    cfg = write_config(clip, seg_ver)
    shp = write_masks(clip, seg_ver, cfg)
    name = r2s_name(clip)
    logs = ROOT / 'outputs' / 'logs'
    logs.mkdir(parents=True, exist_ok=True)
    for target in (name, f'{name}+sift'):
        with open(logs / f'{target}_prep.log', 'w') as f:
            p = subprocess.run([sys.executable, '-m', 'r2s', target, 'prep'], stdout=f, stderr=subprocess.STDOUT, cwd=logs,
                               env=dict(__import__('os').environ, PYTHONPATH=str(ROOT)))
        print(target, 'prep exit', p.returncode, flush=True)
        if p.returncode:
            return p.returncode
    return 0


if __name__ == '__main__':
    sys.exit(run(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else 'v02'))
